### ISSUE TITLE
Hello World

### ISSUE THREAD

**Issue by HugoRodriguesQW** [Animesports/animesports#1]
### To-do

- [x] **Design & Protótipo de projeto**
  - [x] Landing page
  - [x] Login/Register
  - [x] Soccer
  - [x] Leadboard
  - [x] Leagues
  - [x] Rules
  - [x] Account
  - [x] Admin

---

- [ ] **Estrutura básica de renderização**
  - [x] Landing page
  - [x] Login/Register
  - [x] Soccer
  - [x] Leadboard
  - [x] Leagues
  - [ ] Rules
  - [x] Account
  - [x] **Admin**
    - [x] Index
    - [x] Calendar
    - [x] Users
    - [x]  Payments
  - [x] **Popups & Components**
     - [x] QRcode
     - [x] Game details (andamento, encerrado, aberto)
     - [x] Account info update
     - [x] Account email check
     - [x] Empty component
 
---
- [ ] **Lógica**
  - [x] Lógica básica de renderização (incompleto)
  - [x] Controle de sessão
    - [x] Registro de usuário
    - [x] Login
    - [x] Remover usuário
    - [x]  Admin
    - [x] Configurações
  - [x] Controle do jogo
  - [x] Controle de pagamento
  - [ ] Controle de premiação

---
- [ ] **Estrutura final**
  - [ ] Default error pages
  - [ ] Privacy etc
